### ISSUE TITLE
path-0.5.11 test suite failures

### ISSUE THREAD

**Issue by peti** [commercialhaskell/path#48] opened 2016-12-30 18:17 UTC
Citing from https://hydra.nixos.org/build/45670155/nixlog/46/raw:

~~~
Failures:

  test/Main.hs:217: 
  1) Parsing: Path Rel Dir Produces valid paths when it succeeds
       predicate failed on: "\198\236\184d\SOH\DEL\rq\vctZ\247\182..l\160dZcbG\244Lg\250\DC3/]\198\&1{j$\159DP\177\CAN8%\DC3\139\DLE\205z\210\149\239\175\SOXY/" (after 91 tests): 
       "\198\236\184d\SOH\DEL\rq\vctZ\247\182..l\160dZcbG\244Lg\250\DC3/]\198\&1{j$\159DP\177\CAN8%\DC3\139\DLE\205z\210\149\239\175\SOXY"

  test/Main.hs:273: 
  2) Parsing: Path Rel File Produces valid paths when it succeeds
       predicate failed on: "\198\236\184d\SOH\DEL\rq\vctZ\247\182..l\160dZcbG\244Lg\250\DC3/]\198\&1{j$\159DP\177\CAN8%\DC3\139\DLE\205z\210\149\239\175\SOXY" (after 91 tests): 
       "\198\236\184d\SOH\DEL\rq\vctZ\247\182..l\160dZcbG\244Lg\250\DC3/]\198\&1{j$\159DP\177\CAN8%\DC3\139\DLE\205z\210\149\239\175\SOXY"

Randomized with seed 2145543625
~~~

**Comment by peti** [comment] 2017-02-07 16:48
Citing from https://hydra.nixos.org/build/47923567:

~~~
Failures:

  test/Main.hs:217: 
  1) Parsing: Path Rel Dir Produces valid paths when it succeeds
       predicate failed on: "k\204 s\206c&\ESC\188\"\218\DC1@i\184\161\178\251\133DZZ,n;\DC3\155=\129\134&hH;..\n\DC3w\210t&\230\211\144\STXt\165\&2X\SIpx\137m\176/" (after 96 tests): 
       "k\204 s\206c&\ESC\188\"\218\DC1@i\184\161\178\251\133DZZ,n;\DC3\155=\129\134&hH;..\n\DC3w\210t&\230\211\144\STXt\165\&2X\SIpx\137m\176"

  test/Main.hs:273: 
  2) Parsing: Path Rel File Produces valid paths when it succeeds
       predicate failed on: "k\204 s\206c&\ESC\188\"\218\DC1@i\184\161\178\251\133DZZ,n;\DC3\155=\129\134&hH;..\n\DC3w\210t&\230\211\144\STXt\165\&2X\SIpx\137m\176" (after 96 tests): 
       "k\204 s\206c&\ESC\188\"\218\DC1@i\184\161\178\251\133DZZ,n;\DC3\155=\129\134&hH;..\n\DC3w\210t&\230\211\144\STXt\165\&2X\SIpx\137m\176"

Randomized with seed 1845101959
~~~~

**Comment by sjakobi** [comment] 2017-03-03 18:32
Looks like a duplicate of #37.

**Closed by sjakobi** 2017-03-03 18:32 UTC
Labels: bug
